# -*- coding: utf-8 -*-
"""MultiLabel classification using KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZW1qbcUcB6MnHHxG-Mh5g-6hQ3SG6Bj
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, hamming_loss

# Load dataset
aspects_df = pd.read_csv("/semeval2014.csv")
# Input text
X = aspects_df["text"]
# Aspect labels
y = np.asarray(aspects_df[aspects_df.columns[1:]])
# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer(max_features=3000,max_df=0.85)
# Fit TF-IDF
vectorizer.fit(X)
# Split dataset
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size=0.30,random_state=42)

X_train_tfidf = vectorizer.transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Multilabel KNN model
model = OneVsRestClassifier(KNeighborsClassifier(n_neighbors=5))
# Train model
model.fit(X_train_tfidf,y_train
)

new_sentences = ["I like the food but I hate the place"]
# Convert sentence to TF-IDF
new_sentence_tfidf = vectorizer.transform(new_sentences)
# Predict aspects
predicted_sentences = model.predict(new_sentence_tfidf)
print(predicted_sentences)

# Predictions on test data
predicted = model.predict(X_test_tfidf)
# Accuracy
print("Accuracy:",accuracy_score(y_test, predicted))
# Hamming Loss
print("Hamming Loss:",hamming_loss(y_test, predicted))

